### ISSUE TITLE
Updating initramfs with fido2 parameter in crypttab

### ISSUE THREAD

**Issue by ghost** [ricardobranco777/howtos#1]
Hello Ricardo,

This is regarding the [LUKSFIDO2.md](https://github.com/ricardobranco777/howtos/blob/master/LUKSFIDO2.md). I saw that you are not updating the initramfs after adding entry to `/etc/crypttab` file. Should't we re-create the initramfs after this step? Otherwise cryptsetup doesn’t recognize the `fido2-device` option right as described in [https://www.guyrutenberg.com/2022/02/17/unlock-luks-volume-with-a-yubikey/](https://www.guyrutenberg.com/2022/02/17/unlock-luks-volume-with-a-yubikey/). ?

**Comment by ricardobranco777** [comment]
> Hello Ricardo,
> 
> This is regarding the [LUKSFIDO2.md](https://github.com/ricardobranco777/howtos/blob/master/LUKSFIDO2.md). I saw that you are not updating the initramfs after adding entry to `/etc/crypttab` file. Should't we re-create the initramfs after this step? Otherwise cryptsetup doesn’t recognize the `fido2-device` option right as described in https://www.guyrutenberg.com/2022/02/17/unlock-luks-volume-with-a-yubikey/. ?

This is redundant on Raspberry Pi because these settings are read from cmdline.txt.  I could add it as it's harmless so the instructions would work on other systems.

**Comment by ghost** [comment]
Ah okay. That's correct. Could you please let me know what to add in the `cmdline.txt` file for fido2? I am trying this with deafult Raspbian setup (no ZFS).

**Comment by ghost** [comment]
Also, have you tried to do the decryption using a HSM like Nitrokey smartcard using PKCS#11?

**Comment by ghost** [comment]
I have some issue with this setup. Below is my `cmdline.txt`

```
console=serial0,115200 root=/dev/mapper/rootfs cryptopts=target=rootfs,source=/dev/mmcblk0p2,discard,key=/dev/null,fido2-device=auto rootfstype=ext4 fsck.repair=yes rootwait
```

The `/etc/crypttab` is:
```
# <target name>	<source device>		<key file>	<options>
rootfs	/dev/mmcblk0p2	none	luks,fido2-device=auto
```

But when boot, the kernel cannot find the rootfs and I get:
```
unable to find /dev/root
No root device specified. Boot arguments must include a root= parameter.
kernel panic --- could not find the root fs
```

Should we keep the `/dev/mmcblk0p2` entry in `/etc/fstab` ?

I am also using `u-boot`.
Do you have any idea what is missing here?

Thanks in advance

**Comment by ricardobranco777** [comment]
> Should we keep the `/dev/mmcblk0p2` entry in `/etc/fstab` ?

No because this is the encrypted partition.  You need /dev/mapper/rootfs pointing to /.

> I am also using `u-boot`. Do you have any idea what is missing here?

I haven't used u-boot.

**Comment by ghost** [comment]
Okay. So in your setup did you add `/dev/mapper/crypt` pointing to `/` in `/etc/fstab` file? I couldn't find this in the [LUKSFIDO2.md](https://github.com/ricardobranco777/howtos/blob/master/LUKSFIDO2.md)

**Comment by ricardobranco777** [comment]
> Okay. So in your setup did you add `/dev/mapper/crypt` pointing to `/` in `/etc/fstab` file? I couldn't find this in the [LUKSFIDO2.md](https://github.com/ricardobranco777/howtos/blob/master/LUKSFIDO2.md)

I didn't because it's optional with ZFS. I will add this step.

**Comment by ghost** [comment]
Thanks for the update.

I amde some progress and `/dev/mapper/rootfs` pointing to `/` in `/etc/fstab`. But i have weird problem now. I can't get the prompt to enter the password and also `fido2-device=auto` in `cmdline.txt` otpion seems to be ignored. Below is my `cmdline.txt`

```
console=serial0,115200 root=/dev/mapper/rootfs cryptopts=target=rootfs,source=/dev/mmcblk0p2,discard,key=/dev/null,fido2-device=auto rootfstype=ext4 fsck.repair=yes rootwait
```

And this is log I get during boot.

```
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
Nothing to read on input.
cryptsetup: ERROR: rootfs: cryptsetup failed, bad password or options?
cryptsetup: ERROR: rootfs: maximum number of tries exceeded
done.
Begin: Running /scripts/local-premount ... done.
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
Nothing to read on input.
cryptsetup: ERROR: rootfs: cryptsetup failed, bad password or options?
cryptsetup: ERROR: rootfs: maximum number of tries exceeded
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  /dev/mapper/rootfs does not exist.  Dropping to a shell!
``` 

And `/etc/crypttab`

```
# <target name> <source device>         <key file>      <options>
rootfs  /dev/mmcblk0p2  /dev/null       discard,fido2-device=auto
```

Is there anything that I missed in the cmdline.txt file?

**Comment by ricardobranco777** [comment]
> I amde some progress and `/dev/mapper/rootfs` pointing to `/` in `/etc/fstab`. But i have weird problem now. I can't get the prompt to enter the password and also `fido2-device=auto` in `cmdline.txt` otpion seems to be ignored. Below is my `cmdline.txt`
> 
> ```
> console=serial0,115200 root=/dev/mapper/rootfs cryptopts=target=rootfs,source=/dev/mmcblk0p2,discard,key=/dev/null,fido2-device=auto rootfstype=ext4 fsck.repair=yes rootwait
> ```

I'm not sure about `rootfstype` being needed.  Also check if the initrd was created properly: 

```
$ lsinitramfs /boot/initrd.img-$(uname -r) | grep -e cryptsetup -e fido
usr/bin/fido2-token
usr/bin/systemd-ask-password
usr/lib/aarch64-linux-gnu/cryptsetup
usr/lib/aarch64-linux-gnu/cryptsetup/libcryptsetup-token-systemd-fido2.so
usr/lib/aarch64-linux-gnu/libcryptsetup.so.12
usr/lib/aarch64-linux-gnu/libcryptsetup.so.12.9.0
usr/lib/aarch64-linux-gnu/libfido2.so.1
usr/lib/aarch64-linux-gnu/libfido2.so.1.12.0
usr/lib/aarch64-linux-gnu/systemd
usr/lib/aarch64-linux-gnu/systemd/libsystemd-shared-254.so
usr/lib/cryptsetup
usr/lib/cryptsetup/askpass
usr/lib/cryptsetup/functions
usr/lib/modprobe.d/systemd.conf
usr/lib/systemd
usr/lib/systemd/network
usr/lib/systemd/network/73-usb-net-by-mac.link
usr/lib/systemd/network/99-default.link
usr/lib/systemd/systemd-cryptsetup
usr/lib/systemd/systemd-udevd
usr/lib/udev/rules.d/60-fido-id.rules
usr/sbin/cryptsetup
```

**Comment by ricardobranco777** [comment]
Perhaps some missing package?  The rsync was done from a SD setup with Ansible: https://github.com/ricardobranco777/ansible-debian

Check the list of packages installed in the .yml with `apt` in them.

**Comment by ghost** [comment]
The result of `lsinitramfs /boot/initrd.img-$(uname -r) | grep -e cryptsetup -e fido`

```
usr/bin/fido2-token
usr/lib/arm-linux-gnueabihf/cryptsetup
usr/lib/arm-linux-gnueabihf/cryptsetup/libcryptsetup-token-systemd-fido2.so
usr/lib/arm-linux-gnueabihf/cryptsetup/libcryptsetup-token-systemd-pkcs11.so
usr/lib/arm-linux-gnueabihf/libcryptsetup.so.12
usr/lib/arm-linux-gnueabihf/libcryptsetup.so.12.9.0
usr/lib/arm-linux-gnueabihf/libfido2.so.1
usr/lib/arm-linux-gnueabihf/libfido2.so.1.12.0
usr/lib/cryptsetup
usr/lib/cryptsetup/askpass
usr/lib/cryptsetup/functions
usr/lib/systemd/systemd-cryptsetup
usr/lib/udev/rules.d/60-fido-id.rules
usr/sbin/cryptsetup
```

> Check the list of packages installed in the .yml with apt in them.

Sorry, where to check? The packages that I had installed are `cryptsetup initramfs-tools cryptsetup-initramfs fido2-tools`

**Comment by ricardobranco777** [comment]
> The result of `lsinitramfs /boot/initrd.img-$(uname -r) | grep -e cryptsetup -e fido`
> 
> ```
> usr/bin/fido2-token
> usr/lib/arm-linux-gnueabihf/cryptsetup
> usr/lib/arm-linux-gnueabihf/cryptsetup/libcryptsetup-token-systemd-fido2.so
> usr/lib/arm-linux-gnueabihf/cryptsetup/libcryptsetup-token-systemd-pkcs11.so
> usr/lib/arm-linux-gnueabihf/libcryptsetup.so.12
> usr/lib/arm-linux-gnueabihf/libcryptsetup.so.12.9.0
> usr/lib/arm-linux-gnueabihf/libfido2.so.1
> usr/lib/arm-linux-gnueabihf/libfido2.so.1.12.0
> usr/lib/cryptsetup
> usr/lib/cryptsetup/askpass
> usr/lib/cryptsetup/functions
> usr/lib/systemd/systemd-cryptsetup
> usr/lib/udev/rules.d/60-fido-id.rules
> usr/sbin/cryptsetup
> ```

The list seems ok to me.  Was your key detected by the list command?  Are you sure the systemd in the initrd is from backports?  Are you trying PKCS#11?  Does the disk decrypt automatically with FIDO2 key?  

Don't give up.  You may be almost there.

**Comment by ghost** [comment]
Yes, the key is detected and also registered using `systemd-cryptenroll`.

> Are you sure the systemd in the initrd is from backports?

No, the systemd is the deafult from Debian. Is there any reason to install systemd from backports? The systemd version is 
```
systemd 252 (252.17-1~deb12u1+rpi1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```
Also I wonder why I get `WARNING: rootfs: ignoring unknown option 'fido2-device'` message. I have removed it from `/etc/crypttab` as we are passing this from `cmdline.txt`

> Are you trying PKCS#11? 

No, this was for testing a smartcard. I have removed it from `systemd-cryptenroll` now

> Does the disk decrypt automatically with FIDO2 key?

What do you mean by this?

**Comment by ricardobranco777** [comment]
> > Are you sure the systemd in the initrd is from backports?
> 
> No, the systemd is the deafult from Debian. Is there any reason to install systemd from backports?

You absolutely need the 254 version from backports.  See the changelog entry for 253:

https://github.com/systemd/systemd/blob/main/NEWS#L2955

And maybe lots of other stuff is needed too.  Older systemd just doesn't work.

**Comment by ghost** [comment]
installed `systemd 254` from backports and updated initramfs with `update-initramfs -u -k $(uname -r)`. But still the same issue...

During updating initramfs I get below message:

```
cryptsetup: WARNING: Skipping root target rootfs: uses a key file
```

**Comment by ricardobranco777** [comment]
> installed `systemd 254` from backports and updated initramfs with `update-initramfs -u -k $(uname -r)`. But still the same issue...
> 
> During updating initramfs I get below message:
> 
> ```
> cryptsetup: WARNING: Skipping root target rootfs: uses a key file
> ```

Did you try without `rootfstype=ext4` ?  I think it's not needed here when cryptsetup is used.

**Comment by ghost** [comment]
yes, tried without `rootfstype=ext4` . I am not understanding where is the issue?!

**Comment by ricardobranco777** [comment]
> cryptsetup: WARNING: Skipping root target rootfs: uses a key file

I think the problem is the /etc/crypttab entry for /

Try removing it.

**Comment by ghost** [comment]
Tried that. During `update-initramfs` I get `cryptsetup: WARNING: target 'rootfs' not found in /etc/crypttab`

I still get below message during boot
```
Begin: Running /scripts/local-block ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
Nothing to read on input.
```

cryptsetup version is `cryptsetup 2.6.1 flags: UDEV BLKID KEYRING KERNEL_CAPI`

**Comment by ricardobranco777** [comment]
> Tried that. During `update-initramfs` I get `cryptsetup: WARNING: target 'rootfs' not found in /etc/crypttab`

This warning is harmless.

**Comment by ghost** [comment]
one question: should the `/etc/crypttab` file also be part of `initramfs`? The `lsinitramfs /boot/initrd.img-$(uname -r) | grep -e crypttab` shows only `cryptroot/crypttab`

**Comment by ricardobranco777** [comment]
> one question: should the `/etc/crypttab` file also be part of `initramfs`? The `lsinitramfs /boot/initrd.img-$(uname -r) | grep -e crypttab` shows only `cryptroot/crypttab`

Not needed I think.

**Comment by ghost** [comment]
then I am clueless what's the issue is....

**Comment by ghost** [comment]
Do you have any other suggestions for me? I am still stuck with this...

**Comment by ricardobranco777** [comment]
> Do you have any other suggestions for me? I am still stuck with this...

What is the error message you're getting at boot?

**Comment by ghost** [comment]
error message is still the same

```
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
Nothing to read on input.
cryptsetup: ERROR: rootfs: cryptsetup failed, bad password or options?
cryptsetup: ERROR: rootfs: maximum number of tries exceeded
done.
Begin: Running /scripts/local-premount ... done.
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
Nothing to read on input.
cryptsetup: ERROR: rootfs: cryptsetup failed, bad password or options?
cryptsetup: ERROR: rootfs: maximum number of tries exceeded
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  /dev/mapper/rootfs does not exist.  Dropping to a shell!
```

In the initramfs shell I can manually decrypt with `cryptsetup luksOpen /dev/mmcblk0p2 rootfs`. It asks for password and not fido...

**Comment by ricardobranco777** [comment]
> error message is still the same
> 
> ```
> Begin: Mounting root file system ... Begin: Running /scripts/local-top ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
> Nothing to read on input.
> cryptsetup: ERROR: rootfs: cryptsetup failed, bad password or options?
> cryptsetup: ERROR: rootfs: maximum number of tries exceeded
> done.
> Begin: Running /scripts/local-premount ... done.
> Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... cryptsetup: WARNING: rootfs: ignoring unknown option 'fido2-device'
> Nothing to read on input.
> cryptsetup: ERROR: rootfs: cryptsetup failed, bad password or options?
> cryptsetup: ERROR: rootfs: maximum number of tries exceeded
> done.
> Gave up waiting for root file system device.  Common problems:
>  - Boot args (cat /proc/cmdline)
>    - Check rootdelay= (did the system wait long enough?)
>  - Missing modules (cat /proc/modules; ls /dev)
> ALERT!  /dev/mapper/rootfs does not exist.  Dropping to a shell!
> ```
> 
> In the initramfs shell I can manually decrypt with `cryptsetup luksOpen /dev/mmcblk0p2 rootfs`. It asks for password and not fido...

Did you build the initrd after installing systemd from Backports?

**Comment by ghost** [comment]
yes, I have done that

`cmdline.txt`:

```
console=serial0,115200 root=/dev/mapper/rootfs cryptopts=target=rootfs,source=/dev/mmcblk0p2,discard,key=/dev/null,fido2-device=auto rootwait
```

`/etc/fstab`:
```
proc            /proc           proc    defaults          0       0
PARTUUID=d6a5bf45-01  /boot/firmware  vfat    defaults          0       2
# PARTUUID=d6a5bf45-02  /               ext4    defaults,noatime  0       1
/dev/mapper/rootfs      /       ext4    defaults,noatime        0       0
# /dev/mmcblk0p2    /       ext4    defaults,noatime        0       0
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
```

`/etc/crypttab`:
```
# <target name> <source device>         <key file>      <options>
# rootfs        /dev/mmcblk0p2  none    luks,discard,fido2-device=auto

```
These are the settings that I currently have...

**Comment by ricardobranco777** [comment]
I'm lost here, but I'm sure it's pretty stupid.  I was about to give up and then everything was put into place.
